import{Router} from 'express'
const router=Router();
var cors = require('cors')
 
import  {RegistrarUser,MovieLanguage,CreateAvailability,CreateMovie,EliminarTransferencia,getUsuario,ObetenerSegundaTransaccion,EditTransaccion,CreateTransaccion,GetTransaccion,GetPago,CreatePagoAlquiler,UpdateAlquilerPago,CreatePago,DeleteAlquiler,GetAlquiler,UpdateMovie,AddCantidadAlquiler,InsertAlquiler,ExistAlquiler,GetLenguages,GetAvailability,GetMovie,indexInicio,GetMovies, InventarioDePelicula, UsuarioAdmin} from "../controllers/programador1.controller"
 router.route("/")
   .get(indexInicio)
   router.route("/GetMovies")
   .get(GetMovies)
   router.route("/GetMovie")
   .post(GetMovie)
   router.route("/GetLenguages")
   .post(GetLenguages)
   router.route("/GetAvailability")
   .post(GetAvailability)
   router.route("/ExistAlquiler")
   .post(ExistAlquiler)
   router.route("/InsertAlquiler")
   .post(InsertAlquiler)
   router.route("/AddCantidadAlquiler")
   .post(AddCantidadAlquiler)
   router.route("/UpdateMovie")
   .post(UpdateMovie)
   router.route("/GetAlquiler")
   .post(GetAlquiler)
   router.route("/DeleteAlquiler")
   .put(DeleteAlquiler)
   router.route("/CreatePago")
   .post(CreatePago)
   router.route("/UpdateAlquilerPago")
   .post(UpdateAlquilerPago)
   router.route("/GetPago")
   .post(GetPago)
   router.route("/CreatePagoAlquiler")
   .post(CreatePagoAlquiler)
   router.route("/GetTransaccion")
   .post(GetTransaccion)
   router.route("/CreateTransaccion")
   .post(CreateTransaccion)
   router.route("/EditTransaccion")
   .post(EditTransaccion)   
   router.route("/ObetenerSegundaTransaccion")
   .post(ObetenerSegundaTransaccion)   
   router.route("/getUsuario")
   .post(getUsuario)  
   router.route("/EliminarTransferencia")
   .put(EliminarTransferencia) 
   router.route("/CreateMovie")
   .post(CreateMovie)   
   router.route("/CreateAvailability")
   .post(CreateAvailability)  
   router.route("/MovieLanguage")
   .post(MovieLanguage)   
   router.route("/getInventario")
   .post(InventarioDePelicula)  
   router.route("/getAdmin")
   .get(UsuarioAdmin)  
   router.route("/RegistrarUser").post(RegistrarUser)
    export default router;
  